### ISSUE TITLE
How the modular blockchain's module layer should be divided

### ISSUE THREAD

**Issue by jolestar** [rooch-network/rooch-network.github.io#39]
Why do we think the arbitration layer should be split from the settlement layer

### Reference

* [https://twitter.com/jolestar/status/1607956249391554561](https://twitter.com/jolestar/status/1607956249391554561)

**Comment by ren-ryder** [comment]
The industry at large is still working out how to best devise the module layer in the modular blockchain. Let's put this in terms of the evolution of the L2 Rollup. In a typical L2 scenario, there are three main contracts on L1 that take on three roles.

**Role 1**: Cross-layer Bridge, which enables the settlement of assets between L1 and L2.
**Role 2**: Rollup Chain, which contains the L2 transactions and the corresponding state roots.
**Role 3**: Fraud Proof Verification, which rolls back the Rollup Chain's transactions if fraud is determined.

![Image](https://user-images.githubusercontent.com/99104408/217361593-eadb479a-5ef1-495b-910f-7eb86ef0700a.png)

In this way, L2 migrates the execution of transactions from L1 to L2, but the security is guaranteed by a fraud proof contract on L1. The Rollup Chain on L1 exists mainly to guarantee Data Availability (DA). Then the question naturally arises, can these roles be split up and taken on by different modules? Thus the idea of a modular blockchain is born. 

The first thought was to split the Role 2 Rollup Chain to provide a separate Data Available (DA) layer, which is the goal of Celestia. It divides the modular layer into Execution, Settlement, Data Availability (DA) and Consensus layers (which determine the order of transactions). The original L2 becomes the Execution layer, leaving the role 1 cross-layer bridge and the role 3 fraud proof to the Settlement layer.

![Image](https://user-images.githubusercontent.com/99104408/217362014-8cbedd7c-03ae-4442-be8e-d53ac05f8a5b.png)

DA, if it is a separate layer, certainly cannot serve only one chain; it aims to be the DA layer for all chains or applications. So the biggest challenge it faces is to allow applications to verify that their data is available without having to synchronize the full amount of data. The second challenge is that the DA layer needs to have a communication mechanism with the settlement layer. 

Polygon Avail divides the modular layer into a DA (including ensuring transaction sequencing), an execution layer, and a Dispute Resolution (DR) layer. the DR layer is primarily for verifying proof of fraud. It corresponds to role 3 in the previous diagram as a separate layer, but its whitepaper does not describe how asset settlement should be performed. 

![Image](https://user-images.githubusercontent.com/99104408/217362980-9cce03a5-d5ba-467b-b125-f5669a984e39.png)

The industry is still figuring out how the settlement layer should be designed and what responsibilities it should take on. One option is not to rely on an independent settlement layer, such as Sovereign Rollup, where security is guaranteed by the application itself, but this is an L1 solution that delegates the DA. Another option is to design a settlement layer specifically for modular blockchain implementation, but this settlement layer also has to be independently secured, and will also face the "bootstrap" problem. 

Since many L1s are already "bootstrapped", it makes more sense to build a modular solution on top of L1s. If the arbitration function is split out separately, it becomes clear that asset settlement is not exclusive and that the execution layer can support multiple chains simultaneously, going from an execution layer for one L1 to an execution layer for all L1s. This is the key improvement of Rooch, and the goal: a more radical modular solution. 

Let's use an analogy to explain this scenario. If L1 is equivalent to a bank, L2 is equivalent to Alipay, and the arbitration contract is equivalent to a court, Alipay can connect to multiple banks for settlement, while if a dispute arises it is decided through a single court, so that the application only needs to dock to Alipay and thus to multiple banks. Of course, the enforcement layer offers the possibility of much more than payments and settlements. 

The settlement layer in Rooch, which only assumes the responsibilities of role 1 and multi-chain settlement, is to deploy cross-layer bridge contracts on each L1, but the key is that the settlement of the cross-layer bridge is bound by the arbitration contract, thus being able to inherit the security of the arbitration layer L1, while the arbitration layer only assumes the responsibilities of role 3. Of course, the split of arbitration and settlement can be designed in a more flexible model, such as switching the arbitration layer according to the decentralization and security changes of L1. 

Of course, Rooch's solution has significant technical challenges. But if we believe in a multi-chain ecosystem in the future, and cross-chain bridges are currently experiencing so many security challenges, we need to explore new ways of converging multi-chain ecosystems. An execution layer for multi-link computing is the most logically compelling solution.

**Comment by jolestar** [comment]
This article will merge with #40.
